sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker version

  - docker build --no-cache -t m9rco/mongodb:3.6.7 -f 3.6.7/Dockerfile 3.6.7/
  - docker run --name mongodb-3.6.7 -d -v $PWD:/app m9rco/mongodb:3.6.7

script:
  - docker exec mongodb-3.6.7 sh -c "apk -V"
